"""
Crew orchestation module.

This module is the entry point for the agentic workflow, and
is responsible for assembling the crew.

Workflow:
    1. Instantiate the agents and tasks
    2. Configure the CrewAI execution process
    3. Handle the overall agentic workflow instantiation
"""
from crewai import Crew, Process

from src.agents.agents import create_agents
from src.agents.tasks import create_tasks


def run_financial_crew(ticker: str) -> str:
    """
    Initialize and execute the financial analysis crews for a specific stock.

    Args:
        A stock ticker.

    Returns:
        A final markdown report generated by the strategist_agent
    """
    quant_agent, strategist_agent = create_agents()

    # Create tasks
    tasks = create_tasks(
        quant_agent=quant_agent,
        strategist_agent=strategist_agent,
        ticker=ticker
    )

    # Assenble the crew
    financial_crew = Crew(
        agents=[quant_agent, strategist_agent],
        tasks=tasks,
        process=Process.sequential,
        verbose=True
    )

    # Start analysis
    print(f"\nStarting financial anlysis for: {ticker}...")
    result = financial_crew.kickoff()

    return result
